// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYEaKjGSlM0gSXHErS252stRN3sezE8Cc',
    appId: '1:122705779371:web:15d687f842544bb00435ee',
    messagingSenderId: '122705779371',
    projectId: 'saadtest-dd38b',
    authDomain: 'saadtest-dd38b.firebaseapp.com',
    storageBucket: 'saadtest-dd38b.firebasestorage.app',
    measurementId: 'G-DK62L0Z84J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXVKezxtJEWD8a_T4UONRENOEsnBBOEEw',
    appId: '1:122705779371:android:b211e58759323a020435ee',
    messagingSenderId: '122705779371',
    projectId: 'saadtest-dd38b',
    storageBucket: 'saadtest-dd38b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgEgOZ6XSvgNUHugm3GWDZcgIAGgkXPsg',
    appId: '1:122705779371:ios:e1553cf126db0fac0435ee',
    messagingSenderId: '122705779371',
    projectId: 'saadtest-dd38b',
    storageBucket: 'saadtest-dd38b.firebasestorage.app',
    iosBundleId: 'com.example.saadTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgEgOZ6XSvgNUHugm3GWDZcgIAGgkXPsg',
    appId: '1:122705779371:ios:e1553cf126db0fac0435ee',
    messagingSenderId: '122705779371',
    projectId: 'saadtest-dd38b',
    storageBucket: 'saadtest-dd38b.firebasestorage.app',
    iosBundleId: 'com.example.saadTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYEaKjGSlM0gSXHErS252stRN3sezE8Cc',
    appId: '1:122705779371:web:040baa636fb3c7df0435ee',
    messagingSenderId: '122705779371',
    projectId: 'saadtest-dd38b',
    authDomain: 'saadtest-dd38b.firebaseapp.com',
    storageBucket: 'saadtest-dd38b.firebasestorage.app',
    measurementId: 'G-D7W708RHNE',
  );
}
